### ISSUE TITLE
Crashing on respawn

### ISSUE THREAD

**Issue by Frosttfire** [berbb/PortAIO#18]
Playing Tahm Kench, no output in console, 100% reproduced on my end, version 130, everything is enabled AIO wise
E : tested on Ahri Blitz Kalista, 100% as well on those champs.

**Comment by saladinaazir** [comment]
can confirm, happened to me too. I turned off the utility suite, and it stopped.

**Comment by GreatWhite181** [comment]
+1 Happened on all champs I used as well

**Comment by berbb** [comment]
I'll check this out, this is critical.

**Comment by berbb** [comment]
I've pushed a fix, please update it. Respond back to this if its happening.

**Comment by Frosttfire** [comment]
Updated, still crashing on respawn, same 4 champs, 100%.

**Comment by berbb** [comment]
I'm testing it with Ahri and I can't reproduce it.

**Comment by Frosttfire** [comment]
Is there nowhere besides the console that has logs? I see the loader has it's own startup logs, any detailed assembly logging anywhere? I figure if it's not in the console though it won't matter. Just uninstalled everything and reinstalled, Ahri as test, 2 deaths, everything enabled, no items, not facing off against any enemy champs, still crashing.

**Comment by berbb** [comment]
@Frosttfire Thanks, with the information you gave me i'll try to reproduce.

**Comment by berbb** [comment]
Yeah unfortunately, I can't reproduce it, I have everything reinstalled, I'm playing Ahri, every single util addon is enabled on the PortAIO misc, I have no items and no enemies. I'm not sure how to proceed.

**Comment by berbb** [comment]
I'm not sure if this is useful at all but are you playing on full screen? If you are try borderless.

**Comment by Frosttfire** [comment]
I'm on borderless, but I just got into another custom, ahri again, no items, everything on, no enemies, and I've stopped crashing, in an hour or two I'm going to do some comprehensive testing, because nothing has changed since 10 minutes ago.

**Comment by berbb** [comment]
@Frosttfire I'm thrilled to hear that! I'm hopeful that the results of the test will be positive :)

**Comment by iNubbish** [comment]
Playing Zed here, still crashing on respawn.

**Comment by GreatWhite181** [comment]
I was still crashing even with utility suite turned off. I then turned off god jungle tracker and skin changer and its fine now

**Comment by iNubbish** [comment]
Even with those two utilities off I still get crashes on respawn >~<

**Comment by berbb** [comment]
I'm honestly not sure why it's crashing throughout all my times of testing this AIO I haven't crashed on respawn a single time.
